name: Build

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Setup swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.9"
      - uses: actions/checkout@v4
      - name: Build
        run: swift build